/* =========================================================
   PLN Smart Grid Dashboard — Tailwind Theme Config
   Berisi design tokens: warna, spacing, font, dan ukuran teks.
   File ini di-load sebelum tag <script src="https://cdn.tailwindcss.com">
   dipakai, atau setelahnya sebelum konten di-render (lihat index.html).
   ========================================================= */

tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#001e2f",
        "tertiary-fixed": "#c9e6ff",
        "secondary-container": "#d6e3fe",
        "primary-container": "#0066cc",
        "primary-fixed-dim": "#aac7ff",
        "surface-variant": "#d3e4fe",
        "surface-container-low": "#eff4ff",
        "on-surface": "#0b1c30",
        "inverse-surface": "#213145",
        "surface-dim": "#cbdbf5",
        "on-secondary-container": "#58657b",
        error: "#ba1a1a",
        "inverse-primary": "#aac7ff",
        "on-secondary-fixed-variant": "#3a475c",
        "on-surface-variant": "#414753",
        "on-primary-container": "#dfe8ff",
        "outline-variant": "#c1c6d5",
        primary: "#004e9f",
        "on-primary": "#ffffff",
        "on-tertiary-container": "#d4ebff",
        "on-background": "#0b1c30",
        "tertiary-fixed-dim": "#89ceff",
        "surface-container": "#e5eeff",
        "primary-fixed": "#d7e3ff",
        "surface-container-highest": "#d3e4fe",
        "on-primary-fixed-variant": "#00458e",
        "tertiary-container": "#006f9f",
        "surface-bright": "#f8f9ff",
        "on-secondary-fixed": "#0e1c2f",
        "error-container": "#ffdad6",
        "secondary-fixed-dim": "#bac7e1",
        "on-tertiary-fixed-variant": "#004c6e",
        "on-error": "#ffffff",
        background: "#f8f9ff",
        tertiary: "#00567c",
        "on-secondary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        outline: "#727784",
        "on-primary-fixed": "#001b3e",
        "inverse-on-surface": "#eaf1ff",
        "on-tertiary": "#ffffff",
        "surface-tint": "#005cba",
        "on-error-container": "#93000a",
        "secondary-fixed": "#d6e3fe",
        "surface-container-high": "#dce9ff",
        secondary: "#525f75",
        surface: "#f8f9ff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "space-4xl": "3rem",
        "space-3xl": "2.5rem",
        "gutter-tablet": "1rem",
        "margin-desktop": "2rem",
        "margin-mobile": "1rem",
        "space-md": "0.75rem",
        "space-xl": "1.5rem",
        "space-base": "1rem",
        "space-lg": "1.25rem",
        "space-sm": "0.5rem",
        "space-xs": "0.25rem",
        "gutter-desktop": "1.5rem",
        "space-2xs": "0.125rem",
        "space-2xl": "2rem",
      },
      fontFamily: {
        "title-md": ["Inter"],
        "label-sm": ["Inter"],
        "headline-lg": ["Inter"],
        "title-sm": ["Inter"],
        "body-lg": ["Inter"],
        "body-md": ["Inter"],
        "headline-md": ["Inter"],
        "display-lg": ["Inter"],
        "display-lg-mobile": ["Inter"],
        "headline-sm": ["Inter"],
        "body-sm": ["Inter"],
        "label-md": ["Inter"],
        "telemetry-data": ["Inter"],
      },
      fontSize: {
        "title-md": ["16px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.04em", fontWeight: "600" }],
        "headline-lg": ["28px", { lineHeight: "36px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "title-sm": ["14px", { lineHeight: "20px", letterSpacing: "0.005em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", letterSpacing: "0em", fontWeight: "400" }],
        "headline-md": ["22px", { lineHeight: "30px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "display-lg": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-lg-mobile": ["28px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-sm": ["18px", { lineHeight: "26px", letterSpacing: "-0.005em", fontWeight: "600" }],
        "body-sm": ["13px", { lineHeight: "18px", letterSpacing: "0.01em", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "600" }],
        "telemetry-data": ["14px", { lineHeight: "20px", letterSpacing: "-0.01em", fontWeight: "500" }],
      },
    },
  },
};
